### ISSUE TITLE
Incompatible Licensing Restrictions

### ISSUE THREAD

**Issue by HigasaMitsue** [Tsukina-7mochi/aseprite-scripts#8]
Both the `LICENSE.md` and each project directory claim that all scripts are MIT licensed.

However, all `.lua` files contain this in their header: `DO NOT redistribute this code`

In addition, the `README.md` files explicitly state:

> - You cannot redistribute files with no change without my permission.

This is in direct contradiction with the MIT License: 

> Permission is hereby granted [...] to deal in the Software **without restriction**, including **without limitation** the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software [...]

As of right now I have to treat the repo as effectively unlicensed, as the stricter restriction is usually what applies. Would it be possible to clear up this licensing issue?

**Comment by Tsukina-7mochi** [comment]
Thank you for pointing out the contradiction.

I have intended to prohibit distributing the copy of script file, based on MIT license (I think it not likable to spread out dated version of script). 
I'm going to edit `LICSNSE.md` so that the redistribution is to be prohibited other than the methods prepared by GitHub.

I would appreciate if you can give me some opinion.

**Comment by HigasaMitsue** [comment]
Thank you for the quick response. While I understand your worry, I believe it is unrealistic to prevent the distribution of older versions.

Instead, open source licenses (such as MIT, BSD, Apache) encourage contribution by others back to the original author, so that the program can improve over time. The licenses works both ways - by agreeing to license their changes under an open license, they are allowing their code to be used in yours without restriction. Using a standard open source license therefore makes it very easy for others to contribute to the project.

I believe it would be more productive to properly adopt the MIT license than remove it, but as the current sole author of the code you have final say, of course.

**Comment by LunaTheFoxgirl** [comment]
I think this is very bad for open source contribution, as such if you want to restrict people with what they can do with the script you should probably not release it on GitHub.

Additionally there's bugs in this script that I know people can fix, which they will be discouraged from contributing when they know their code is not open.

**Comment by Tsukina-7mochi** [comment]
Thank you for your opinion. I've understood there's not a good way to encourage people to visit original source instead of cloning old version of script (Please note that I do NOT want to restrict contributing of other people and there is a rule to allow cloning and modifying in GitHub).

Also there's no way to check updates of script for Aseprite, I'll just delete the description of prohibiting cloning.
